apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-backend
  template:
    metadata:
      labels:
        app: bookstore-backend
    spec:
      containers:
        - name: backend
          image: your-docker-username/bookstore-backend:latest # REPLACE WITH YOUR IMAGE
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: bookstore-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP # Internal only